name: Registration PR

on:
  pull_request:
    branches:
      - main

  merge_group:
  workflow_dispatch:

jobs:
  test:
    name: Build And Test
    uses: ./.github/workflows/build.yml
    secrets: inherit
