name: Push

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Build And Test
    uses: ./.github/workflows/build.yml
    secrets: inherit

  publish:
    needs: [test]
    permissions:
      contents: read
      packages: write
    name: Publish latest tag
    uses: ./.github/workflows/publish-latest.yml
    secrets: inherit
